name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    - name: Install backend
      run: |
        cd backend
        npm install

    - name: Build Docker image
      run: docker build -t yourusername/carental-05:latest .

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker image
      run: docker push yourusername/carental-05:latest

    - name: Deploy to Fly.io
      uses: superfly/flyctl-actions@1.1
      with:
        args: "deploy"
      env:
        FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
